-- Schema Oracle 21c XE per il database "ditta_trasporti" (porting da PostgreSQL)
-- Base: DATABASE/Sistema1/backup_18-06-2024.sql (schema piu recente, coerente con le entity JPA attuali:
-- turni.id_utente sostituisce turni.matricola presente invece nel vecchio Sistema1/init.sql)
-- Gli script in questa cartella girano come SYSDBA connesso al CDB root: serve entrare nella PDB e nello schema applicativo.
ALTER SESSION SET CONTAINER = XEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = ditta_trasporti;

CREATE TABLE linee (
    num_linea    NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    destinazione VARCHAR2(30) NOT NULL,
    CONSTRAINT linee_pkey PRIMARY KEY (num_linea)
);

CREATE TABLE autobus (
    targa    VARCHAR2(10) NOT NULL,
    modello  VARCHAR2(20) NOT NULL,
    capienza NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT autobus_pkey PRIMARY KEY (targa)
);

CREATE TABLE utenti (
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY START WITH 1 INCREMENT BY 1,
    username VARCHAR2(30) NOT NULL,
    password VARCHAR2(30) NOT NULL,
    ruolo    VARCHAR2(7) DEFAULT 'AUTISTA' NOT NULL,
    CONSTRAINT utenti_pkey PRIMARY KEY (id)
);

CREATE TABLE autisti (
    matricola VARCHAR2(5) NOT NULL,
    cognome   VARCHAR2(30) NOT NULL,
    nome      VARCHAR2(25) NOT NULL,
    telefono  VARCHAR2(10),
    id_utente NUMBER NOT NULL,
    CONSTRAINT autisti_pkey PRIMARY KEY (matricola),
    CONSTRAINT autisti_id_utente_key UNIQUE (id_utente),
    CONSTRAINT autisti_id_utente_fkey FOREIGN KEY (id_utente) REFERENCES utenti (id) ON DELETE CASCADE
);

-- "ora_inizio"/"ora_fine" sono di tipo DATE: Oracle non ha un tipo TIME nativo, il driver JDBC
-- mappa java.sql.Time su DATE usando una data convenzionale (1970-01-01) e conserva solo l'orario.
CREATE TABLE turni (
    id         NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1,
    data       DATE NOT NULL,
    ora_inizio DATE NOT NULL,
    ora_fine   DATE NOT NULL,
    targa      VARCHAR2(10) NOT NULL,
    num_linea  NUMBER NOT NULL,
    id_utente  NUMBER NOT NULL,
    CONSTRAINT turni_pkey PRIMARY KEY (id),
    CONSTRAINT turni_id_targa_numlinea_idutente_key UNIQUE (id, targa, num_linea, id_utente),
    CONSTRAINT turni_autisti_id_utente_fkey FOREIGN KEY (id_utente) REFERENCES autisti (id_utente),
    CONSTRAINT turni_autobus_targa_fkey FOREIGN KEY (targa) REFERENCES autobus (targa) ON DELETE CASCADE,
    CONSTRAINT turni_linee_num_linea_fkey FOREIGN KEY (num_linea) REFERENCES linee (num_linea)
);

