version: '3.8'
services:
  db:
    image: gvenzl/oracle-xe:21-slim
    container_name: db_oracle_ditta_trasporti
    environment:
      ORACLE_PASSWORD: password
      APP_USER: ditta_trasporti
      APP_USER_PASSWORD: password
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle-init:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  oracle_data:
